package Consts_MapPin

const (
	MapPin           = "mapPin"
	Badge            = "badge"
	Burger           = "burger"
	Cry_Woman        = "cry_woman"
	Fret             = "fret"
	Gal              = "gal"
	Kanon            = "kanon"
	Kariya           = "kariya"
	Kubo             = "kubo"
	Minamimoto       = "minamimoto"
	Nagi             = "nagi"
	Rindo            = "rindo"
	Shinigami        = "shinigami"
	Uzuki            = "uzuki"
	Noise_Bear       = "noise_bear"
	Noise_Chameleon  = "noise_chameleon"
	Noise_Crow       = "noise_crow"
	Noise_Elephant   = "noise_elephant"
	Noise_Frog       = "noise_frog"
	Noise_Gorilla    = "noise_gorilla"
	Noise_Harisenbon = "noise_harisenbon"
	Noise_Jellyfish  = "noise_jellyfish"
	Noise_Rhino      = "noise_rhino"
	Noise_Scorpion   = "noise_scorpion"
	Noise_Shark      = "noise_shark"
	Noise_Tyranno    = "noise_tyranno"
	Noise_Wolf       = "noise_wolf"
)
