package Consts_MapPinColor

const (
	MapPin_Color_Sub   = "pin_sub"
	Noise_Frog_R       = "01_R"
	Noise_Frog_B       = "01_B"
	Noise_Frog_Y       = "01_Y"
	Noise_Jellyfish_R  = "02_R"
	Noise_Jellyfish_B  = "02_B"
	Noise_Jellyfish_Y  = "02_Y"
	Noise_Bear_R       = "03_R"
	Noise_Bear_B       = "03_B"
	Noise_Bear_Y       = "03_Y"
	Noise_Wolf_R       = "04_R"
	Noise_Wolf_B       = "04_B"
	Noise_Wolf_Y       = "04_Y"
	Noise_Crow_R       = "05_R"
	Noise_Crow_B       = "05_B"
	Noise_Crow_Y       = "05_Y"
	Noise_Chameleon_R  = "06_R"
	Noise_Chameleon_B  = "06_B"
	Noise_Chameleon_Y  = "06_Y"
	Noise_Shark_R      = "07_R"
	Noise_Shark_B      = "07_B"
	Noise_Shark_Y      = "07_Y"
	Noise_Tyranno_R    = "08_R"
	Noise_Tyranno_B    = "08_B"
	Noise_Tyranno_Y    = "08_Y"
	Noise_Elephant_R   = "09_R"
	Noise_Elephant_B   = "09_B"
	Noise_Elephant_Y   = "09_Y"
	Noise_Harisenbon_R = "10_R"
	Noise_Harisenbon_B = "10_B"
	Noise_Harisenbon_Y = "10_Y"
	Noise_Scorpion_R   = "11_R"
	Noise_Scorpion_B   = "11_B"
	Noise_Scorpion_Y   = "11_Y"

	//These colors aren't actually any different but eh
	Noise_Gorilla_R  = "12_R"
	Noise_Gorilla_B  = "12_B"
	Noise_Gorilla_Y  = "12_Y"
	Noise_Gorilla2_R = "13_R"
	Noise_Gorilla2_B = "13_B"
	Noise_Gorilla2_Y = "13_Y"
	Noise_Rhino_R    = "14_R"
	Noise_Rhino_B    = "14_B"
	Noise_Rhino_Y    = "14_Y"
)
