// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Teams struct {
	TeamID   sql.NullString
	RoomID   sql.NullString
	TeamName sql.NullString
}

type UserBuildings struct {
	UserID sql.NullString
	Prefab sql.NullString
	Name   sql.NullString
	Status sql.NullString
}

type UserCharacters struct {
	UserID      sql.NullString
	CharacterId sql.NullInt64
	ItemId      sql.NullInt64
}

type UserGPS struct {
	UserID         sql.NullString
	ID             sql.NullString
	Name           sql.NullString
	PinType        sql.NullString
	PinColor       sql.NullString
	Latitude       sql.NullFloat64
	Longitude      sql.NullFloat64
	LuaScript      sql.NullInt64
	BLocationEvent sql.NullInt64
	QuestID        sql.NullInt64
	MapType        sql.NullString
	MapNo          sql.NullString
	IsRemove       sql.NullInt64
}

type UserItems struct {
	UserID sql.NullString
	Item   sql.NullInt64
}

type UserLocalMap struct {
	UserID sql.NullString
	Name   sql.NullString
	Floor  sql.NullInt64
}

type UserOnceEvent struct {
	UserID   sql.NullString
	UInt     sql.NullInt64
	IsRemove sql.NullInt64
}

type UserQuest struct {
	UserID sql.NullString
	ID     sql.NullInt64
	Value  sql.NullInt64
}

type UserQuestItems struct {
	UserID  sql.NullString
	QuestID sql.NullInt64
	Name    sql.NullString
	Type    sql.NullString
}

type UserResume struct {
	UserID   sql.NullString
	BResume  sql.NullInt64
	LuaHash  sql.NullInt64
	TagID    sql.NullInt64
	ResumeID sql.NullInt64
}

type UserSave struct {
	UserID    sql.NullString
	BIntro    sql.NullInt64
	NowHP     sql.NullInt64
	MaxHP     sql.NullInt64
	ColorID   sql.NullInt64
	BNewQuest sql.NullInt64
	AItemList sql.NullString
}

type UserScans struct {
	UserID   sql.NullString
	ID       sql.NullInt64
	Type     sql.NullInt64
	Tag      sql.NullString
	Height   sql.NullFloat64
	BMulti   sql.NullInt64
	LuaHash  sql.NullInt64
	IsRemove sql.NullInt64
}

type Users struct {
	DeviceID sql.NullString
	ID       sql.NullString
	Name     sql.NullString
	Status   sql.NullInt64
	TeamID   sql.NullString
	NewGame  sql.NullInt64
	UUID     sql.NullString
}
